
-- -----------------------------------------------------
-- Schema VIAGENS_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VIAGENS_DB` ;
USE `VIAGENS_DB` ;

-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`MINISTERIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`MINISTERIO` (
  `ID_MINISTERIO` INT NOT NULL,
  `NOME` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`ID_MINISTERIO`),
  UNIQUE INDEX `ID_MINISTERIO_UNIQUE` (`ID_MINISTERIO` ASC),
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC));


-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`PESSOA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`PESSOA` (
  `ID_PESSOA` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(128) NOT NULL,
  `CPF` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID_PESSOA`),
  UNIQUE INDEX `ID_PESSOA_UNIQUE` (`ID_PESSOA` ASC),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC));


-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`CARGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`CARGO` (
  `ID_CARGO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`ID_CARGO`),
  UNIQUE INDEX `ID_CARGO_UNIQUE` (`ID_CARGO` ASC),
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC));


-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`FUNCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`FUNCAO` (
  `ID_FUNCAO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(128) NOT NULL,
  `DESCRICAO` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`ID_FUNCAO`),
  UNIQUE INDEX `ID_FUNCAO_UNIQUE` (`ID_FUNCAO` ASC),
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC));


-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`PESSOA_CARGO_FUNCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`PESSOA_CARGO_FUNCAO` (
  `ID_PESSOA_CARGO_FUNCAO` INT NOT NULL AUTO_INCREMENT,
  `ID_PESSOA` INT NOT NULL,
  `ID_FUNCAO` INT NOT NULL,
  `ID_CARGO` INT NOT NULL,
  PRIMARY KEY (`ID_PESSOA_CARGO_FUNCAO`),
  INDEX `fk_PESSOA_CARGO_FUNCAO_PESSOA1_idx` (`ID_PESSOA` ASC),
  INDEX `fk_PESSOA_CARGO_FUNCAO_FUNCAO1_idx` (`ID_FUNCAO` ASC),
  INDEX `fk_PESSOA_CARGO_FUNCAO_CARGO1_idx` (`ID_CARGO` ASC),
  CONSTRAINT `fk_PESSOA_CARGO_FUNCAO_PESSOA1`
    FOREIGN KEY (`ID_PESSOA`)
    REFERENCES `VIAGENS_DB`.`PESSOA` (`ID_PESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESSOA_CARGO_FUNCAO_FUNCAO1`
    FOREIGN KEY (`ID_FUNCAO`)
    REFERENCES `VIAGENS_DB`.`FUNCAO` (`ID_FUNCAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESSOA_CARGO_FUNCAO_CARGO1`
    FOREIGN KEY (`ID_CARGO`)
    REFERENCES `VIAGENS_DB`.`CARGO` (`ID_CARGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`UF` (
  `ID_UF` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`ID_UF`),
  UNIQUE INDEX `ID_UF_UNIQUE` (`ID_UF` ASC),
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC));


-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`PAIS` (
  `ID_PAIS` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`ID_PAIS`),
  UNIQUE INDEX `ID_PAIS_UNIQUE` (`ID_PAIS` ASC),
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC));


-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`CIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`CIDADE` (
  `ID_CIDADE` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`ID_CIDADE`),
  UNIQUE INDEX `ID_CIDADE_UNIQUE` (`ID_CIDADE` ASC),
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC));


-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`PAIS_CIDADE_UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`PAIS_CIDADE_UF` (
  `ID_PAIS_CIDADE_UF` INT NOT NULL AUTO_INCREMENT,
  `ID_PAIS` INT NOT NULL,
  `ID_UF` INT NOT NULL,
  `ID_CIDADE` INT NOT NULL,
  PRIMARY KEY (`ID_PAIS_CIDADE_UF`),
  INDEX `fk_PAIS_CIDADE_UF_PAIS1_idx` (`ID_PAIS` ASC),
  INDEX `fk_PAIS_CIDADE_UF_UF1_idx` (`ID_UF` ASC),
  INDEX `fk_PAIS_CIDADE_UF_CIDADE1_idx` (`ID_CIDADE` ASC),
  CONSTRAINT `fk_PAIS_CIDADE_UF_PAIS1`
    FOREIGN KEY (`ID_PAIS`)
    REFERENCES `VIAGENS_DB`.`PAIS` (`ID_PAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAIS_CIDADE_UF_UF1`
    FOREIGN KEY (`ID_UF`)
    REFERENCES `VIAGENS_DB`.`UF` (`ID_UF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAIS_CIDADE_UF_CIDADE1`
    FOREIGN KEY (`ID_CIDADE`)
    REFERENCES `VIAGENS_DB`.`CIDADE` (`ID_CIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`MEIO_TRANSPORTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`MEIO_TRANSPORTE` (
  `ID_MEIO_TRANSPORTE` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`ID_MEIO_TRANSPORTE`),
  UNIQUE INDEX `ID_MEIO_TRANSPORTE_UNIQUE` (`ID_MEIO_TRANSPORTE` ASC),
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC));


-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`VIAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`VIAGEM` (
  `ID_VIAGEM` INT NOT NULL,
  `IS_REALIZADO` TINYINT NOT NULL,
  `IS_URGENTE` TINYINT NOT NULL,
  `DATA_INICIO` DATETIME NOT NULL,
  `DATA_FIM` DATETIME NOT NULL,
  `ID_MINISTERIO` INT NOT NULL,
  `ID_PESSOA_CARGO_FUNCAO` INT NOT NULL,
  `TOTAL` FLOAT NULL,
  PRIMARY KEY (`ID_VIAGEM`),
  UNIQUE INDEX `ID_VIAGEM_UNIQUE` (`ID_VIAGEM` ASC),
  INDEX `fk_VIAGEM_MINISTERIOS1_idx` (`ID_MINISTERIO` ASC),
  INDEX `fk_VIAGEM_PESSOA_CARGO_FUNCAO1_idx` (`ID_PESSOA_CARGO_FUNCAO` ASC),
  CONSTRAINT `fk_VIAGEM_MINISTERIOS1`
    FOREIGN KEY (`ID_MINISTERIO`)
    REFERENCES `VIAGENS_DB`.`MINISTERIO` (`ID_MINISTERIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIAGEM_PESSOA_CARGO_FUNCAO1`
    FOREIGN KEY (`ID_PESSOA_CARGO_FUNCAO`)
    REFERENCES `VIAGENS_DB`.`PESSOA_CARGO_FUNCAO` (`ID_PESSOA_CARGO_FUNCAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`PASSAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`PASSAGEM` (
  `ID_PASSAGEM` INT NOT NULL AUTO_INCREMENT,
  `ID_VIAGEM` INT NOT NULL,
  `ID_MEIO_TRANSPORTE` INT NOT NULL,
  `ID_PAIS_CIDADE_UF_ORIGEM_IDA` INT NOT NULL,
  `ID_PAIS_CIDADE_UF_DESTINO_IDA` INT NOT NULL,
  `ID_PAIS_CIDADE_UF_ORIGEM_VOLTA` INT NOT NULL,
  `ID_PAIS_CIDADE_UF_DESTINO_VOLTA` INT NOT NULL,
  PRIMARY KEY (`ID_PASSAGEM`),
  INDEX `fk_PASSAGEM_VIAGEM1_idx` (`ID_VIAGEM` ASC),
  INDEX `fk_PASSAGEM_MEIO_TRANSPORTE1_idx` (`ID_MEIO_TRANSPORTE` ASC),
  INDEX `fk_PASSAGEM_PAIS_CIDADE_UF1_idx` (`ID_PAIS_CIDADE_UF_ORIGEM_IDA` ASC),
  INDEX `fk_PASSAGEM_PAIS_CIDADE_UF2_idx` (`ID_PAIS_CIDADE_UF_DESTINO_IDA` ASC),
  INDEX `fk_PASSAGEM_PAIS_CIDADE_UF3_idx` (`ID_PAIS_CIDADE_UF_ORIGEM_VOLTA` ASC),
  INDEX `fk_PASSAGEM_PAIS_CIDADE_UF4_idx` (`ID_PAIS_CIDADE_UF_DESTINO_VOLTA` ASC),
  CONSTRAINT `fk_PASSAGEM_VIAGEM1`
    FOREIGN KEY (`ID_VIAGEM`)
    REFERENCES `VIAGENS_DB`.`VIAGEM` (`ID_VIAGEM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PASSAGEM_MEIO_TRANSPORTE1`
    FOREIGN KEY (`ID_MEIO_TRANSPORTE`)
    REFERENCES `VIAGENS_DB`.`MEIO_TRANSPORTE` (`ID_MEIO_TRANSPORTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PASSAGEM_PAIS_CIDADE_UF1`
    FOREIGN KEY (`ID_PAIS_CIDADE_UF_ORIGEM_IDA`)
    REFERENCES `VIAGENS_DB`.`PAIS_CIDADE_UF` (`ID_PAIS_CIDADE_UF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PASSAGEM_PAIS_CIDADE_UF2`
    FOREIGN KEY (`ID_PAIS_CIDADE_UF_DESTINO_IDA`)
    REFERENCES `VIAGENS_DB`.`PAIS_CIDADE_UF` (`ID_PAIS_CIDADE_UF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PASSAGEM_PAIS_CIDADE_UF3`
    FOREIGN KEY (`ID_PAIS_CIDADE_UF_ORIGEM_VOLTA`)
    REFERENCES `VIAGENS_DB`.`PAIS_CIDADE_UF` (`ID_PAIS_CIDADE_UF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PASSAGEM_PAIS_CIDADE_UF4`
    FOREIGN KEY (`ID_PAIS_CIDADE_UF_DESTINO_VOLTA`)
    REFERENCES `VIAGENS_DB`.`PAIS_CIDADE_UF` (`ID_PAIS_CIDADE_UF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `VIAGENS_DB`.`PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIAGENS_DB`.`PAGAMENTO` (
  `ID_PAGAMENTO` INT NOT NULL AUTO_INCREMENT,
  `VALOR` FLOAT NOT NULL,
  `TAXA` FLOAT NOT NULL,
  `ID_PASSAGEM` INT NOT NULL,
  PRIMARY KEY (`ID_PAGAMENTO`),
  UNIQUE INDEX `ID_PAGAMENTO_UNIQUE` (`ID_PAGAMENTO` ASC),
  INDEX `fk_PAGAMENTO_PASSAGEM1_idx` (`ID_PASSAGEM` ASC),
  CONSTRAINT `fk_PAGAMENTO_PASSAGEM1`
    FOREIGN KEY (`ID_PASSAGEM`)
    REFERENCES `VIAGENS_DB`.`PASSAGEM` (`ID_PASSAGEM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `VIAGENS_DB`;

DELIMITER $$
USE `VIAGENS_DB`$$
CREATE TRIGGER `VIAGENS_DB`.`PAGAMENTO_AFTER_INSERT` AFTER INSERT ON `PAGAMENTO` FOR EACH ROW
BEGIN
    UPDATE VIAGENS_DB.VIAGEM AS X, VIAGENS_DB.PASSAGEM AS Y, VIAGENS_DB.PAGAMENTO AS Z, (
    	SELECT * FROM (SELECT (SUM(T1.VALOR) + SUM(T1.TAXA)) AS TOTAL, T3.ID_VIAGEM
						FROM VIAGENS_DB.PAGAMENTO T1
						LEFT JOIN VIAGENS_DB.PASSAGEM T2 ON NEW.ID_PASSAGEM = T2.ID_PASSAGEM
						LEFT JOIN VIAGENS_DB.VIAGEM T3 ON T2.ID_VIAGEM = T3.ID_VIAGEM
						WHERE T3.ID_VIAGEM = T2.ID_VIAGEM
						GROUP BY T3.ID_VIAGEM) AS FOO) AS W
    SET X.TOTAL = W.TOTAL
    WHERE X.ID_VIAGEM = Y.ID_VIAGEM AND Y.ID_PASSAGEM = NEW.ID_PASSAGEM;
END$$

USE `VIAGENS_DB`$$
CREATE TRIGGER `VIAGENS_DB`.`PAGAMENTO_AFTER_UPDATE` AFTER UPDATE ON `PAGAMENTO` FOR EACH ROW
BEGIN
    UPDATE VIAGENS_DB.VIAGEM AS X, VIAGENS_DB.PASSAGEM AS Y, VIAGENS_DB.PAGAMENTO AS Z, (
    	SELECT * FROM (SELECT (SUM(T1.VALOR) + SUM(T1.TAXA)) AS TOTAL, T3.ID_VIAGEM
						FROM VIAGENS_DB.PAGAMENTO T1
						LEFT JOIN VIAGENS_DB.PASSAGEM T2 ON NEW.ID_PASSAGEM = T2.ID_PASSAGEM
						LEFT JOIN VIAGENS_DB.VIAGEM T3 ON T2.ID_VIAGEM = T3.ID_VIAGEM
						WHERE T3.ID_VIAGEM = T2.ID_VIAGEM
						GROUP BY T3.ID_VIAGEM) AS FOO) AS W
    SET X.TOTAL = W.TOTAL
    WHERE X.ID_VIAGEM = Y.ID_VIAGEM AND Y.ID_PASSAGEM = NEW.ID_PASSAGEM;
END$$


DELIMITER ;
